module.exports.NewtonCoinIcon = require('./NewtonCoinIcon.js')
module.exports.NewtonLogoFull = require('./NewtonLogoFull.js')
module.exports.WaveMarketLogo = require('./WaveMarketLogo.js')
module.exports.WaveMarketText = require('./WaveMarketText.js')
module.exports.HuobiTokenIcon = require('./HuobiTokenIcon.js')
module.exports.BinanceCoinIcon = require('./BinanceCoinIcon.js')
module.exports.HuobiLogoFull = require('./HuobiLogoFull.js')
module.exports.BinanceLogoFull = require('./BinanceLogoFull.js')
